### ISSUE TITLE
Conflict with package Flowpack.Neos.FrontendLogin

### ISSUE THREAD

**Issue by DrillSergeant** [psmb/Psmb.FlatNav#12]
When using this package together with the neos frontendlogin-package you will run into this problem:

The ajax-route "flatnav/query?..." is not considered a backend-route by the frontendlogin-package and your login-token is not active for the ajax-route. Problem is the way how  Flowpack\Neos\FrontendLogin\Security\NeosRequestPattern (see https://github.com/Flowpack/Flowpack.Neos.FrontendLogin/blob/master/Classes/Flowpack/Neos/FrontendLogin/Security/NeosRequestPattern.php#L53) identifies be-routes.

My solution was to disable the frontendlogin requestpattern for the Neos-Backend provider:
```
Neos:
  Flow:
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'Flowpack.Neos.FrontendLogin:NeosBackend': ~
```
By doing this, you might not be able to login via frontendlogin-form as a backend-user. For me not a problem as I don't use this feature.

Maybe this should be mentioned somewhere in the readme. The frontendlogin-package has no issues enabled in github, otherwise I would informed there as well.
