### ISSUE TITLE
Get 'Your login has expired. Please log in again.' when loading flat nav tab

### ISSUE THREAD

**Issue by simonschaufi** [psmb/Psmb.FlatNav#29]
Neos version: 5.0.5
Logged in as Admin

While the page tree loads fine, when I click on the flat nav tab i created, I immediately get the login screen overlay.

This is my settings.yaml of my package

```yaml
Neos:
  Neos:
    Ui:
      frontendConfiguration:
        Psmb_FlatNav:
          presets:
            blogPosts:
              label: 'Blog posts'
              icon: newspaper
              type: flat
              query: 'q(node).find("[instanceof RobertLemke.Plugin.Blog:Post]").sort("datePublished", "DESC").slice((page - 1) * 20, page * 20).get()'
              newReferenceNodePath: 'q(node).find("[instanceof RobertLemke.Plugin.Blog:Post]").first().get(0).path'
              newNodeType: 'RobertLemke.Plugin.Blog:Post'
              disablePagination: true
```
