### ISSUE TITLE
Allow restricting access to FlatNav configuration by role

### ISSUE THREAD

**Issue by lorenzulrich** [psmb/Psmb.FlatNav#41]
Sometimes, you want to use FlatNav for a node type but restrict access to certain roles. Imagine having a News system allowing to set Tags. You want News and Tags to be defined in a FlatNav tab, but Tags only edited by adminstrators, not by normal editors.

```
events:
  label: Events
  icon: ticket
  type: flat
  query: 'q(node).find("[instanceof My.Site:Page.EventItem]").sort("date", "DESC").slice((page - 1) * 100, page * 100).get()'
  newReferenceNodePath: '/sites/my/node-58dcfb662cb42'
  newNodeType: 'My.Site:Page.EventItem'
categories:
  label: Categories
  icon: tags
  type: flat
  query: 'q(node).find("[instanceof My.Site:Page.Category]").sort("title", "DESC").slice((page - 1) * 100, page * 100).get()'
  newReferenceNodePath: '/sites/my/node-89j0mu3a57lgn'
  newNodeType: 'My.Site:Page.Category'
  restrictToRoles: ['Neos.Neos:Administrator']
```

By default, a FlatNav would be visible for all authenticated users. Therefore a new setting `restrictToRoles` (or similar) would be backwards-compatible.

By the way: I'm aware that this will not provide security for the affected nodes. It only allows displaying or not the FlatNav based on a role. The user will still need to configure CreateNodePrivilege, EditNodePrivilege and RemoveNodePrivilege to prevent users from modifying such records through the API.
