### ISSUE TITLE
Control the destination on click

### ISSUE THREAD

**Issue by signalwerk** [psmb/Psmb.FlatNav#51]
I have a structure where I have several pages and inside the pages I have products. 

![image](https://user-images.githubusercontent.com/992878/128618930-0e445b5f-4758-4a76-8195-8cc14ce0c893.png)

NodeTypes are like that: 

```

vendor.project:Document.Page
└── vendor.project:Content.Product

vendor.project:Document.Page
└── vendor.project:Content.Product

```

I would like to see in FlatNav all the Products and when I click on the item in the list I would like to see the Page with the product in it. 

I thought with `q(node).closest("[instanceof vendor.project:Document.Page]").get(0).path` I could get it but maybe I missunderstand that. How can I control the destionation when clicking on the node?

`Settings.yaml`

```yaml
tags:
  label: Tags
  icon: tag
  type: flat
  query: 'q(node).find("[instanceof vendor.project:Content.Product]").sort("title", "ASC").slice((page - 1) * 20, page * 20).get()'
  newReferenceNodePath: 'q(node).closest("[instanceof vendor.project:Document.Page]").get(0).path'
  newNodeType: 'vendor.project:Content.Product'
```
